apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: ueransim-gnb
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-29T09:52:52Z"
  generation: 1
  labels:
    app.kubernetes.io/component: gnb
    app.kubernetes.io/instance: ueransim-gnb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ueransim-gnb
    helm.sh/chart: ueransim-gnb-0.2.6
  name: ueransim-gnb
  namespace: default
  resourceVersion: "6176112"
  uid: 97e8c031-2309-42db-9efa-50349b268a2b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: gnb
      app.kubernetes.io/instance: ueransim-gnb
      app.kubernetes.io/name: ueransim-gnb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: gnb
        app.kubernetes.io/instance: ueransim-gnb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ueransim-gnb1
        helm.sh/chart: ueransim-gnb-0.2.6
    spec:
      containers:
      - args:
        - gnb
        env:
        - name: AMF_HOSTNAME
          value: open5gs-amf-ngap
        - name: N2_IFACE
          value: eth0
        - name: N3_IFACE
          value: eth0
        - name: RADIO_IFACE
          value: eth0
        image: docker.io/gradiant/ueransim:3.2.6
        imagePullPolicy: Always
        name: gnodeb
        ports:
        - containerPort: 4997
          name: gnb-ue
          protocol: UDP
        - containerPort: 2152
          name: gnb-upf
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ueransim/gnb.yaml
          name: config
          subPath: gnb.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ueransim-gnb
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-29T09:52:52Z"
    lastUpdateTime: "2024-09-29T09:53:28Z"
    message: ReplicaSet "ueransim-gnb-cdf9649df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-09-29T10:12:02Z"
    lastUpdateTime: "2024-09-29T10:12:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
