apiVersion: v1
data:
  gnb.yaml: |
    mcc: 999 # Mobile Country Code value
    mnc: 70 # Mobile Network Code value (2 or 3 digits)

    nci: '0x0000000100'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 0001             # Tracking Area Code

    linkIp: 192.168.130.10   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: 192.168.130.10  # gNB's local IP address for N2 Interface (Usually same with local IP)
    gtpIp: 192.168.130.10   # gNB's local IP address for N3 Interface (Usually same with local IP)

    # List of AMF address information
    amfConfigs:

      - address: 172.16.245.245
        port: 38412

    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1


    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: ueransim-gnb
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-29T09:52:52Z"
  labels:
    app.kubernetes.io/component: gnb
    app.kubernetes.io/instance: ueransim-gnb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ueransim-gnb
    helm.sh/chart: ueransim-gnb-0.2.6
  name: ueransim-gnb
  namespace: default
  resourceVersion: "6621371"
  uid: b3bf3516-9a7e-42b9-ab86-294caf1ca1d4
