apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"ueransim-gnb","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2024-09-29T09:52:52Z","generation":1,"labels":{"app.kubernetes.io/component":"ues","app.kubernetes.io/instance":"ueransim-gnb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ueransim-gnb","argocd.argoproj.io/instance":"ueransimtiral2","helm.sh/chart":"ueransim-gnb-0.2.6"},"name":"ueransim-gnb-ues","namespace":"default","resourceVersion":"6199957","uid":"364bcfea-bb16-45f5-878b-3edc1f8bda87"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"ues","app.kubernetes.io/instance":"ueransim-gnb","app.kubernetes.io/name":"ueransim-gnb"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"ues","app.kubernetes.io/instance":"ueransim-gnb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ueransim-gnb","helm.sh/chart":"ueransim-gnb-0.2.6"}},"spec":{"containers":[{"args":["ue","-n","2"],"env":[{"name":"GNB_HOSTNAME","value":"ueransim-gnb"}],"image":"docker.io/gradiant/ueransim:3.2.6","imagePullPolicy":"Always","name":"ues","resources":{},"securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/ueransim/ue.yaml","name":"config","subPath":"ue.yaml"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"ueransim-gnb1"},"name":"config"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-09-29T09:52:52Z","lastUpdateTime":"2024-09-29T09:53:29Z","message":"ReplicaSet \"ueransim-gnb-ues-6c55cf58d6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-09-29T12:36:47Z","lastUpdateTime":"2024-09-29T12:36:47Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: ueransim-gnb
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-29T09:52:52Z"
  generation: 2
  labels:
    app.kubernetes.io/component: ues
    app.kubernetes.io/instance: ueransim-gnb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ueransim-gnb
    argocd.argoproj.io/instance: ueransimtiral2
    helm.sh/chart: ueransim-gnb-0.2.6
  name: ueransim-gnb-ues
  namespace: default
  resourceVersion: "6906334"
  uid: 364bcfea-bb16-45f5-878b-3edc1f8bda87
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: ues
      app.kubernetes.io/instance: ueransim-gnb
      app.kubernetes.io/name: ueransim-gnb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ues
        app.kubernetes.io/instance: ueransim-gnb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ueransim-gnb
        helm.sh/chart: ueransim-gnb-0.2.6
    spec:
      containers:
      - args:
        - ue
        - -n
        - "2"
        env:
        - name: GNB_HOSTNAME
          value: ueransim-gnb
        image: docker.io/gradiant/ueransim:3.2.6
        imagePullPolicy: Always
        name: ues
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ueransim/ue.yaml
          name: config
          subPath: ue.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ueransim-gnb1
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-29T12:36:47Z"
    lastUpdateTime: "2024-09-29T12:36:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-29T09:52:52Z"
    lastUpdateTime: "2024-10-02T14:35:03Z"
    message: ReplicaSet "ueransim-gnb-ues-79964895d5" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
